### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by badcat** [brianhaferkamp/skmmr#28]
Love skimmr :)  thanks.

Often many stories do not seem to have an image getting pulled in from NewsAPI.org feeds? and we're left with a broken image.  Perhaps a fallback image could be added?  

Edit: To note, some feeds like Rueters have their own fallback image, while ABC News does not.
¯\_(ツ)_/¯

**Comment by brianhaferkamp** [comment]
Yes, I've noticed the same thing. I made a half-hearted attempt at a fallback image. I'll get back on it.

**Comment by brianhaferkamp** [comment]
Okay. I created a fallback image to show when the image source is null. Thanks for submitting the issue.
