### ISSUE TITLE
Newsletter Signup area is different from live page

### ISSUE THREAD

**Issue by JaidenDeChon** [brianhaferkamp/skmmr#49]
I noticed the code here may be missing some elements that are present on the live site. This is causing the newsletter children (email form & submit button) to be not centered and stacked on top of each other. 

The CSS selector, `#mc_embed_signup`, appears to be the parent for both of them.

**Comment by brianhaferkamp** [comment]
Thanks again for looking into this. Since v2, I've taken out the newsletter signup form so this is no longer relevant to the project.
